"""Alembic script template — 由 env.py 使用"""
# This file is a Mako template

revision = '9a288366c564'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_events', sa.Column('task_completion_status', sa.Text(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_events', 'task_completion_status')
    # ### end Alembic commands ###
